#!/bin/bash

sxhkd &
setxkbmap -model pc105 -layout us,gr -variant qwerty -option grp:alt_shift_toggle &
setxkbmap us &

if pgrep picom; then killall picom; fi
picom --experimental-backends --backend glx &

start-pulseaudio-x11 &
nm-applet &
nitrogen --restore &

/usr/bin/dunst &

if pgrep polybar; then killall polybar; fi
polybar bspwm &

if pgrep flashfocus; then killall flashfocus; fi
flashfocus &

xsetroot -cursor_name left_ptr &

/bin/discord &

bspc config focus_follows_pointer true
bspc config border_width         1
bspc config window_gap           10
bspc config single_monocle true
bspc config single_borderless true
bspc config single_gapless true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a krita desktop='^5'
bspc rule -a REAPER desktop='^4'
bspc rule -a discord desktop='^9' focus=no
bspc rule -a QjackCtl desktop='^8'
bspc rule -a firefox desktop='^1'
bspc rule -a mplayer2 state=floating

bspc monitor -d I II III IV V VI VII VIII IX X

if pgrep jackd; then killall jackd; fi
if pgrep jackdbus; then killall jackdbus; fi

~/bin/start_jack.sh

