#!/bin/bash

if pgrep polybar; then killall polybar; fi
polybar bspwm &

xsetroot -cursor_name left_ptr &

#bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true
bspc config border_width         1
bspc config window_gap           35
bspc config single_monocle true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a krita desktop='^5'
bspc rule -a mpv state=floating
bspc rule -a REAPER desktop='^4'
bspc rule -a spotify desktop='^7' focus=no
bspc rule -a discord desktop='^9' focus=no
bspc rule -a QjackCtl desktop='^8'
bspc rule -a qutebrowser desktop='^2'
bspc rule -a mplayer2 state=floating


bspc monitor -d 1 2 3 4 5 6 7 8 9

#if pidof watch; then killall watch; fi
#watch -n 3600 ~/bin/auto_theme_changer.sh &

discord &

nm-applet &

#if [ -d "$HOME/.cache/wal" ]; then
#    wal -R
#else
#    $HOME/bin/theme_changer.sh -d $HOME/Pictures/nerdy.jpg
#fi

