#!/bin/bash

if pgrep polybar; then killall polybar; fi
polybar bspwm &

nm-applet &

xsetroot -cursor_name left_ptr &



#bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true
bspc config border_width         1
bspc config window_gap           25
bspc config single_monocle true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a krita desktop='^'
bspc rule -a mpv state=floating
bspc rule -a REAPER desktop='^4'
bspc rule -a discord desktop='^' focus=no
bspc rule -a QjackCtl desktop='^ﬓ'
bspc rule -a firefox desktop='^'
bspc rule -a qutebrowser desktop='^'
bspc rule -a mplayer2 state=floating


bspc monitor -d      ﬓ ﬓ ﬓ 

if pidof watch; then killall watch; fi
watch -n 3600 ~/bin/auto_theme_changer.sh &

discord &
